Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102006.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102007.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102009.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102013.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102018.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102020.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102033.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102034.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102052.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102069.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102074.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102089.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102091.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102086.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102096.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102101.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102104.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102116.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102119.pkl'
Traceback (most recent call last):
  File "src/3d/continue_int.py", line 254, in <module>
    continue_integration(filename)
  File "src/3d/continue_int.py", line 15, in continue_integration
    with open(data_dir + filename + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/uufs/chpc.utah.edu/common/home/u0946770/thesis/reg_stokeslets/data/bd_run/bd_run3102123.pkl'
